# 11.1 ndarray Manipulation -1


In [147]:
import numpy as np
arr = np.random.randint(1,100, size = (10,5)) #sample = 10, feature = 5
print(arr.shape)
print(arr)
print(arr.ndim)

(10, 5)
[[85 44 14  8 35]
 [ 7  9 52 98 85]
 [90 93 42 44 13]
 [79 43 78 30  1]
 [82 72 25  6 48]
 [21 45 79 86 87]
 [49 23 34  1 71]
 [61  7 83 39 28]
 [45 21 69 92 56]
 [47 32 76  7 16]]
2


In [148]:
# Changing shape
b = arr.reshape(2,25)
print(b.shape)
print(b)
print(b.ndim)

(2, 25)
[[85 44 14  8 35  7  9 52 98 85 90 93 42 44 13 79 43 78 30  1 82 72 25  6
  48]
 [21 45 79 86 87 49 23 34  1 71 61  7 83 39 28 45 21 69 92 56 47 32 76  7
  16]]
2


In [149]:
# Changing Dimension
# 1D
flatten = b.flatten()
print(flatten)

[85 44 14  8 35  7  9 52 98 85 90 93 42 44 13 79 43 78 30  1 82 72 25  6
 48 21 45 79 86 87 49 23 34  1 71 61  7 83 39 28 45 21 69 92 56 47 32 76
  7 16]


In [150]:
column_wise_flattening = np.ravel(b, order= 'F')
print(column_wise_flattening)

[85 21 44 45 14 79  8 86 35 87  7 49  9 23 52 34 98  1 85 71 90 61 93  7
 42 83 44 39 13 28 79 45 43 21 78 69 30 92  1 56 82 47 72 32 25 76  6  7
 48 16]


In [151]:
a = np.random.randint(1,10, size = (2,3))
b = np.random.randint(20,30, size = (2,3))

print(a)
print(b)

[[8 2 6]
 [8 4 5]]
[[25 23 23]
 [20 22 28]]


In [152]:
# Concatenat


con = np.concatenate((a,b), axis = 0) #row wise
print(con)
con_c = np.concatenate((a,b), axis = 1) #Column wise
print(con_c)

[[ 8  2  6]
 [ 8  4  5]
 [25 23 23]
 [20 22 28]]
[[ 8  2  6 25 23 23]
 [ 8  4  5 20 22 28]]


# 11.2 ndarray Manipulation - 2


In [153]:
# Transpose
mat = np.array([[100,20,30],[30,400,50]])

Transpose = mat.T
print(Transpose)

[[100  30]
 [ 20 400]
 [ 30  50]]


In [154]:
#Array split

a = np.random.randint(1,10, size= (10,))
print(a)

[3 4 8 5 3 2 9 2 7 5]


In [155]:
splitted_array = np.array_split(a, 3)
print(splitted_array)

[array([3, 4, 8, 5], dtype=int32), array([3, 2, 9], dtype=int32), array([2, 7, 5], dtype=int32)]


# 11.3 ndarray Arithmetic Operators and Mathematical function

In [156]:
#mathematical operator
#Faster for vectorization
x = np.array([10,20,30,40])
y = np.array([2,3,4,5])

add = x+y

print(add)

sub = x-y

print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

rem = x%y
print(rem)

[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [157]:
#mathematical function

#trigonometry
sin_val = np.sin(x)
cos_val = np.cos(x)
tan_val = np.tan(x)

print(sin_val)
print(cos_val)
print(tan_val)


[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493]


In [158]:
#Converting Degree<->Radian
#radian to degree
deg_con = np.rad2deg(x)
print(deg_con)
#degree to radian
red_con = np.deg2rad(x)
print(red_con)

[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]
[0.17453293 0.34906585 0.52359878 0.6981317 ]


In [159]:
#log
print(x)
bas_10_log = np.log10(x)
print(bas_10_log)

bas_2_log = np.log2(x)
print(bas_2_log)

[10 20 30 40]
[1.         1.30103    1.47712125 1.60205999]
[3.32192809 4.32192809 4.9068906  5.32192809]


In [160]:
#Square root

sqr_rt = np.sqrt(x)
print(sqr_rt)

sum = np.sum(x)
print(sum)
c_sum = np.cumulative_sum(x)
print(c_sum)

[3.16227766 4.47213595 5.47722558 6.32455532]
100
[ 10  30  60 100]


# 11.4 Numpy Broadcasting

In [161]:
x  = np.array([10,8,16,10])

result = x+2
print(result)

[12 10 18 12]


In [162]:
print(mat)
matrix = mat
result = matrix + 2
print(result)

vector = np.array([1,2,3])
result = matrix + vector
print(result)

[[100  20  30]
 [ 30 400  50]]
[[102  22  32]
 [ 32 402  52]]
[[101  22  33]
 [ 31 402  53]]


# 11.5 Numpy Logical Functions

In [163]:
greatter_than = x>y
print(greatter_than)

[ True  True  True  True]


In [164]:
print(np.all(greatter_than))
print(np.any(greatter_than))

True
True


# 11.6 ndarray Sorting


In [165]:
#Inplace sorting

print(x)

z = x.copy()
print(z)
z.sort()

print(z)

[10  8 16 10]
[10  8 16 10]
[ 8 10 10 16]


In [166]:
# Copy sort
print(x)
sort_arr = np.sort(x)
print(sort_arr)
print(x)

[10  8 16 10]
[ 8 10 10 16]
[10  8 16 10]


In [167]:
#2D array sorting

print(mat)

n_mat = mat
#horizon  axis = 1

hor_sort=np.sort(mat, axis=1)
print(hor_sort)

#verticat
vert_sort = np.sort(mat, axis=0)
print(vert_sort)


[[100  20  30]
 [ 30 400  50]]
[[ 20  30 100]
 [ 30  50 400]]
[[ 30  20  30]
 [100 400  50]]


# 11.7 ndarray Searching

In [168]:
print(x)

index = np.where(x==16)
print(index)
index = np.where(x>8)#return index
print(index)

[10  8 16 10]
(array([2]),)
(array([0, 2, 3]),)


In [169]:
#If value is less than 8 , rewrite as 0
arr = np.where(x>8,x,0)#returns array
print(arr)

[10  0 16 10]


In [170]:
print(mat)

[[100  20  30]
 [ 30 400  50]]


In [171]:
index = np.where(mat>80)#return index
print(index)
index = np.where(mat>80,mat,0)#return index
print(index)

(array([0, 1]), array([0, 1]))
[[100   0   0]
 [  0 400   0]]


In [172]:
#max value index
print(x)
max_val = np.argmax(x)
print(max_val)

[10  8 16 10]
2


In [173]:
#min value index
print(x)
min_val = np.argmin(x)
print(min_val)

[10  8 16 10]
1


# 11.8 ndarray Counting

In [174]:
arr_1d = np.random.randint(1,100, size=(100,))
print(arr_1d)

[61 67 25 20 24 48 53 57 12  4 57 31 28 24 92 89 38 21 36 69 50 81 73 23
  8 19 26  4 13 66 25 67 47 71 15 83 21 86 84 32 79 19 41 67 65 45 45 62
 66 34 13 77 73 55 95 59 65 87  8  4 90 96 54 18 30 97  7 25 82 54 31 58
 26 67 84 34 89 23 77 85 84 71 30 57 11  8 69 64 83 22 98 58 68 16 84 30
 93 12 60 62]


In [180]:
value_gr_60 = np.count_nonzero(arr_1d==7)
print(value_gr_60)

1


In [181]:
unq_val,count = np.unique(arr_1d,return_counts=True)
print(unq_val)
print(count)

[ 4  7  8 11 12 13 15 16 18 19 20 21 22 23 24 25 26 28 30 31 32 34 36 38
 41 45 47 48 50 53 54 55 57 58 59 60 61 62 64 65 66 67 68 69 71 73 77 79
 81 82 83 84 85 86 87 89 90 92 93 95 96 97 98]
[3 1 3 1 2 2 1 1 1 2 1 2 1 2 2 3 2 1 3 2 1 2 1 1 1 2 1 1 1 1 2 1 3 2 1 1 1
 2 1 2 2 4 1 2 2 2 2 1 1 1 2 4 1 1 1 2 1 1 1 1 1 1 1]
