# 11.1 ndarray Manipulation -1


In [37]:
import numpy as np
arr = np.random.randint(1,100, size = (10,5)) #sample = 10, feature = 5
print(arr.shape)
print(arr)
print(arr.ndim)

(10, 5)
[[34 63 69 12 34]
 [26 20  4 97 42]
 [19 41 65 11 23]
 [ 6 10 89 73 78]
 [16 34 36 97 19]
 [70 93 10 54 27]
 [35 79 38 37 19]
 [36 60 77  7 91]
 [64 73 24 56 18]
 [ 7 83 98 86 65]]
2


In [38]:
# Changing shape
b = arr.reshape(2,25)
print(b.shape)
print(b)
print(b.ndim)

(2, 25)
[[34 63 69 12 34 26 20  4 97 42 19 41 65 11 23  6 10 89 73 78 16 34 36 97
  19]
 [70 93 10 54 27 35 79 38 37 19 36 60 77  7 91 64 73 24 56 18  7 83 98 86
  65]]
2


In [39]:
# Changing Dimension
# 1D
flatten = b.flatten()
print(flatten)

[34 63 69 12 34 26 20  4 97 42 19 41 65 11 23  6 10 89 73 78 16 34 36 97
 19 70 93 10 54 27 35 79 38 37 19 36 60 77  7 91 64 73 24 56 18  7 83 98
 86 65]


In [40]:
column_wise_flattening = np.ravel(b, order= 'F')
print(column_wise_flattening)

[34 70 63 93 69 10 12 54 34 27 26 35 20 79  4 38 97 37 42 19 19 36 41 60
 65 77 11  7 23 91  6 64 10 73 89 24 73 56 78 18 16  7 34 83 36 98 97 86
 19 65]


In [41]:
a = np.random.randint(1,10, size = (2,3))
b = np.random.randint(20,30, size = (2,3))

print(a)
print(b)

[[8 4 2]
 [5 7 6]]
[[26 29 26]
 [29 27 20]]


In [42]:
# Concatenat


con = np.concatenate((a,b), axis = 0) #row wise
print(con)
con_c = np.concatenate((a,b), axis = 1) #Column wise
print(con_c)

[[ 8  4  2]
 [ 5  7  6]
 [26 29 26]
 [29 27 20]]
[[ 8  4  2 26 29 26]
 [ 5  7  6 29 27 20]]


# 11.2 ndarray Manipulation - 2


In [43]:
# Transpose
mat = np.array([[100,20,30],[30,400,50]])

Transpose = mat.T
print(Transpose)

[[100  30]
 [ 20 400]
 [ 30  50]]


In [44]:
#Array split

a = np.random.randint(1,10, size= (10,))
print(a)

[2 9 6 5 5 6 6 7 2 9]


In [45]:
splitted_array = np.array_split(a, 3)
print(splitted_array)

[array([2, 9, 6, 5], dtype=int32), array([5, 6, 6], dtype=int32), array([7, 2, 9], dtype=int32)]


# 11.3 ndarray Arithmetic Operators and Mathematical function

In [46]:
#mathematical operator
#Faster for vectorization
x = np.array([10,20,30,40])
y = np.array([2,3,4,5])

add = x+y

print(add)

sub = x-y

print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

rem = x%y
print(rem)

[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [47]:
#mathematical function

#trigonometry
sin_val = np.sin(x)
cos_val = np.cos(x)
tan_val = np.tan(x)

print(sin_val)
print(cos_val)
print(tan_val)


[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493]


In [48]:
#Converting Degree<->Radian
#radian to degree
deg_con = np.rad2deg(x)
print(deg_con)
#degree to radian
red_con = np.deg2rad(x)
print(red_con)

[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]
[0.17453293 0.34906585 0.52359878 0.6981317 ]


In [49]:
#log
print(x)
bas_10_log = np.log10(x)
print(bas_10_log)

bas_2_log = np.log2(x)
print(bas_2_log)

[10 20 30 40]
[1.         1.30103    1.47712125 1.60205999]
[3.32192809 4.32192809 4.9068906  5.32192809]


In [50]:
#Square root

sqr_rt = np.sqrt(x)
print(sqr_rt)

sum = np.sum(x)
print(sum)
c_sum = np.cumulative_sum(x)
print(c_sum)

[3.16227766 4.47213595 5.47722558 6.32455532]
100
[ 10  30  60 100]


# 11.4 Numpy Broadcasting

In [51]:
x  = np.array([10,8,16,10])

result = x+2
print(result)

[12 10 18 12]


In [52]:
print(mat)
matrix = mat
result = matrix + 2
print(result)

vector = np.array([1,2,3])
result = matrix + vector
print(result)

[[100  20  30]
 [ 30 400  50]]
[[102  22  32]
 [ 32 402  52]]
[[101  22  33]
 [ 31 402  53]]


# 11.5 Numpy Logical Functions

In [53]:
greatter_than = x>y
print(greatter_than)

[ True  True  True  True]


In [54]:
print(np.all(greatter_than))
print(np.any(greatter_than))

True
True


# 11.6 ndarray Sorting


In [55]:
#Inplace sorting

print(x)

z = x.copy()
print(z)
z.sort()

print(z)

[10  8 16 10]
[10  8 16 10]
[ 8 10 10 16]


In [56]:
# Copy sort
print(x)
sort_arr = np.sort(x)
print(sort_arr)
print(x)

[10  8 16 10]
[ 8 10 10 16]
[10  8 16 10]


In [57]:
#2D array sorting

print(mat)

n_mat = mat
#horizon  axis = 1

hor_sort=np.sort(mat, axis=1)
print(hor_sort)

#verticat
vert_sort = np.sort(mat, axis=0)
print(vert_sort)


[[100  20  30]
 [ 30 400  50]]
[[ 20  30 100]
 [ 30  50 400]]
[[ 30  20  30]
 [100 400  50]]


# 11.7 ndarray Searching

In [58]:
print(x)

index = np.where(x==16)
print(index)
index = np.where(x>8)#return index
print(index)

[10  8 16 10]
(array([2]),)
(array([0, 2, 3]),)


In [59]:
#If value is less than 8 , rewrite as 0
arr = np.where(x>8,x,0)#returns array
print(arr)

[10  0 16 10]


In [60]:
print(mat)

[[100  20  30]
 [ 30 400  50]]


In [61]:
index = np.where(mat>80)#return index
print(index)
index = np.where(mat>80,mat,0)#return index
print(index)

(array([0, 1]), array([0, 1]))
[[100   0   0]
 [  0 400   0]]


In [62]:
#max value index
print(x)
max_val = np.argmax(x)
print(max_val)

[10  8 16 10]
2


In [63]:
#min value index
print(x)
min_val = np.argmin(x)
print(min_val)

[10  8 16 10]
1


# 11.8 ndarray Counting

In [64]:
arr_1d = np.random.randint(1,100, size=(100,))
print(arr_1d)

[72 16 84 13 21 38 37 56 97  5 80 13 68 18 97 86 99  5 22 23 60 13 50 79
 43 32 71 90 52 37 35 15 70 65 50 62 86  1 41 90 88 95 34 22 63 17 55 79
 87 38 16 62 27 27 78  3 23 42 78 54 97 40 55 37 80 97 70 27 20 26 97 95
 15 55 62 70 12 98 93 21 96 58  1 42 48 67 49  9 33 66 10 32 33 50 29 76
 29 77 69 15]


In [65]:
value_gr_60 = np.count_nonzero(arr_1d==7)
print(value_gr_60)

0


In [66]:
unq_val,count = np.unique(arr_1d,return_counts=True)
print(unq_val)
print(count)

[ 1  3  5  9 10 12 13 15 16 17 18 20 21 22 23 26 27 29 32 33 34 35 37 38
 40 41 42 43 48 49 50 52 54 55 56 58 60 62 63 65 66 67 68 69 70 71 72 76
 77 78 79 80 84 86 87 88 90 93 95 96 97 98 99]
[2 1 2 1 1 1 3 3 2 1 1 1 2 2 2 1 3 2 2 2 1 1 3 2 1 1 2 1 1 1 3 1 1 3 1 1 1
 3 1 1 1 1 1 1 3 1 1 1 1 2 2 2 1 2 1 1 2 1 2 1 5 1 1]


# 11.9 Statistical function

In [67]:
#data loading
data = np.genfromtxt('students_scores.csv',delimiter=',', skip_header=1)
print(data)


[[  1.  56.  97.  42.]
 [  2.  44.  81.  55.]
 [  3.  78.  88.  72.]
 [  4.  90.  97.  79.]
 [  5.  83.  98.  40.]
 [  6.  60.  49.  91.]
 [  7.  83.  96.  58.]
 [  8.  68.  53.  87.]
 [  9.  74.  62.  88.]
 [ 10.  64.  56.  93.]
 [ 11.  47.  43.  60.]
 [ 12.  84.  56.  42.]
 [ 13.  74.  51.  67.]
 [ 14.  92.  43.  59.]
 [ 15.  86.  98.  59.]
 [ 16.  87.  94.  52.]
 [ 17.  57.  83.  59.]
 [ 18.  57.  83.  51.]
 [ 19.  43.  99.  95.]
 [ 20.  98.  48.  69.]
 [ 21.  80.  57.  65.]
 [ 22.  45.  64.  81.]
 [ 23.  86.  97.  73.]
 [ 24.  50.  86.  98.]
 [ 25.  75.  49.  91.]
 [ 26.  40.  86.  98.]
 [ 27.  97.  80.  67.]
 [ 28.  95.  46.  56.]
 [ 29.  90.  87.  49.]
 [ 30.  87.  60.  96.]
 [ 31.  58.  98.  76.]
 [ 32.  45.  42.  98.]
 [ 33.  93.  53.  86.]
 [ 34.  54.  97.  56.]
 [ 35.  89.  55.  76.]
 [ 36.  77.  46.  56.]
 [ 37.  71.  45.  89.]
 [ 38.  54.  96.  75.]
 [ 39.  64.  83.  77.]
 [ 40.  84.  80.  42.]
 [ 41.  69.  81.  72.]
 [ 42.  54.  81.  88.]
 [ 43.  40.  62.  75.]
 [ 44.  44.

In [68]:
#slicing
math_marks = data[::,1:2]
print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)
min_math_marks = np.min(math_marks)
print(min_math_marks)
avg_math_marks = np.mean(math_marks)
print(avg_math_marks)
median_math_marks = np.median(math_marks)
print(median_math_marks)

#Standard Deviation

std_math_marks = np.std(math_marks)
print(std_math_marks)


[[56. 44. 78. 90. 83. 60. 83. 68. 74. 64. 47. 84. 74. 92. 86. 87. 57. 57.
  43. 98. 80. 45. 86. 50. 75. 40. 97. 95. 90. 87. 58. 45. 93. 54. 89. 77.
  71. 54. 64. 84. 69. 54. 40. 44. 71. 71. 43. 59. 89. 50. 85. 65. 42. 52.
  96. 55. 66. 82. 99. 56. 51. 64. 67. 59. 95. 68. 40. 72. 85. 85. 44. 87.
  66. 71. 89. 56. 57. 58. 80. 92. 87. 91. 66. 65. 77. 86. 66. 46. 68. 52.
  59. 55. 43. 96. 76. 84. 62. 97. 55. 53.]]
99.0
40.0
69.17
68.0
17.122531938939403


In [69]:
# Correlation Matrix

s_hr = np.array([2,4,5,7,8])
e_hr = np.array([65,75,78,88,92])

data = np.array([s_hr,e_hr])

correlation = np.corrcoef(data)
print(f"Correlation Matrix:\n{correlation}")

Correlation Matrix:
[[1.         0.99859154]
 [0.99859154 1.        ]]


# 11.10 Linear Algebra with NumPy


In [70]:
A = np.array([
  [1,2,3],
  [3,4,6],
  [7,8,9]
])

B = np.array([
  [1,2],
  [3,4],
  [7,8]
])

#dot product

dot_p = np.dot(A,B)
print(dot_p)

#trace
print(np.trace(B))


[[ 28  34]
 [ 57  70]
 [ 94 118]]
5


In [71]:
#determinant
sq_mat = np.array([
  [1,2,3],
  [4,5,6],
  [7,8,9]
])
det_of_sq = np.linalg.det(sq_mat)
print(det_of_sq)

0.0


In [72]:
#Rnak
rank_sq = np.linalg.matrix_rank(sq_mat)
print(rank_sq)

2
