# 11.1 ndarray Manipulation -1


In [69]:
import numpy as np
arr = np.random.randint(1,100, size = (10,5)) #sample = 10, feature = 5
print(arr.shape)
print(arr)
print(arr.ndim)

(10, 5)
[[77  4 73 90 47]
 [93 42 18 11 11]
 [79 50 14 17 53]
 [26 94 68 66 12]
 [10 18 35 14 48]
 [87 69 96 65 14]
 [26 17 89 38 48]
 [50 68 18 78 86]
 [50 69 39 79 97]
 [21 38 28 79 95]]
2


In [70]:
# Changing shape
b = arr.reshape(2,25)
print(b.shape)
print(b)
print(b.ndim)

(2, 25)
[[77  4 73 90 47 93 42 18 11 11 79 50 14 17 53 26 94 68 66 12 10 18 35 14
  48]
 [87 69 96 65 14 26 17 89 38 48 50 68 18 78 86 50 69 39 79 97 21 38 28 79
  95]]
2


In [71]:
# Changing Dimension
# 1D
flatten = b.flatten()
print(flatten)

[77  4 73 90 47 93 42 18 11 11 79 50 14 17 53 26 94 68 66 12 10 18 35 14
 48 87 69 96 65 14 26 17 89 38 48 50 68 18 78 86 50 69 39 79 97 21 38 28
 79 95]


In [72]:
column_wise_flattening = np.ravel(b, order= 'F')
print(column_wise_flattening)

[77 87  4 69 73 96 90 65 47 14 93 26 42 17 18 89 11 38 11 48 79 50 50 68
 14 18 17 78 53 86 26 50 94 69 68 39 66 79 12 97 10 21 18 38 35 28 14 79
 48 95]


In [73]:
a = np.random.randint(1,10, size = (2,3))
b = np.random.randint(20,30, size = (2,3))

print(a)
print(b)

[[5 1 1]
 [8 5 5]]
[[28 20 23]
 [23 23 21]]


In [74]:
# Concatenat


con = np.concatenate((a,b), axis = 0) #row wise
print(con)
con_c = np.concatenate((a,b), axis = 1) #Column wise
print(con_c)

[[ 5  1  1]
 [ 8  5  5]
 [28 20 23]
 [23 23 21]]
[[ 5  1  1 28 20 23]
 [ 8  5  5 23 23 21]]


# 11.2 ndarray Manipulation - 2


In [75]:
# Transpose
mat = np.array([[100,20,30],[30,400,50]])

Transpose = mat.T
print(Transpose)

[[100  30]
 [ 20 400]
 [ 30  50]]


In [76]:
#Array split

a = np.random.randint(1,10, size= (10,))
print(a)

[3 1 8 8 4 3 9 2 6 4]


In [77]:
splitted_array = np.array_split(a, 3)
print(splitted_array)

[array([3, 1, 8, 8], dtype=int32), array([4, 3, 9], dtype=int32), array([2, 6, 4], dtype=int32)]


# 11.3 ndarray Arithmetic Operators and Mathematical function

In [78]:
#mathematical operator
#Faster for vectorization
x = np.array([10,20,30,40])
y = np.array([2,3,4,5])

add = x+y

print(add)

sub = x-y

print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

rem = x%y
print(rem)

[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [79]:
#mathematical function

#trigonometry
sin_val = np.sin(x)
cos_val = np.cos(x)
tan_val = np.tan(x)

print(sin_val)
print(cos_val)
print(tan_val)


[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493]


In [80]:
#Converting Degree<->Radian
#radian to degree
deg_con = np.rad2deg(x)
print(deg_con)
#degree to radian
red_con = np.deg2rad(x)
print(red_con)

[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]
[0.17453293 0.34906585 0.52359878 0.6981317 ]


In [81]:
#log
print(x)
bas_10_log = np.log10(x)
print(bas_10_log)

bas_2_log = np.log2(x)
print(bas_2_log)

[10 20 30 40]
[1.         1.30103    1.47712125 1.60205999]
[3.32192809 4.32192809 4.9068906  5.32192809]


In [82]:
#Square root

sqr_rt = np.sqrt(x)
print(sqr_rt)

sum = np.sum(x)
print(sum)
c_sum = np.cumulative_sum(x)
print(c_sum)

[3.16227766 4.47213595 5.47722558 6.32455532]
100
[ 10  30  60 100]


# 11.4 Numpy Broadcasting

In [83]:
x  = np.array([10,8,16,10])

result = x+2
print(result)

[12 10 18 12]


In [84]:
print(mat)
matrix = mat
result = matrix + 2
print(result)

vector = np.array([1,2,3])
result = matrix + vector
print(result)

[[100  20  30]
 [ 30 400  50]]
[[102  22  32]
 [ 32 402  52]]
[[101  22  33]
 [ 31 402  53]]


# 11.5 Numpy Logical Functions

In [85]:
greatter_than = x>y
print(greatter_than)

[ True  True  True  True]


In [86]:
print(np.all(greatter_than))
print(np.any(greatter_than))

True
True


# 11.6 ndarray Sorting


In [87]:
#Inplace sorting

print(x)

z = x.copy()
print(z)
z.sort()

print(z)

[10  8 16 10]
[10  8 16 10]
[ 8 10 10 16]


In [88]:
# Copy sort
print(x)
sort_arr = np.sort(x)
print(sort_arr)
print(x)

[10  8 16 10]
[ 8 10 10 16]
[10  8 16 10]


In [ ]:
#2D array sorting

print(mat)

n_mat = mat
#horizon  axis = 1

hor_sort=np.sort(mat, axis=1)
print(hor_sort)

#verticat
vert_sort = np.sort(mat, axis=0)
print(vert_sort)


[[100  20  30]
 [ 30 400  50]]
[[ 20  30 100]
 [ 30  50 400]]
[[ 30  20  30]
 [100 400  50]]
[[100  20  30]
 [ 30 400  50]]
