# 11.1 ndarray Manipulation -1


In [1]:
import numpy as np
arr = np.random.randint(1,100, size = (10,5)) #sample = 10, feature = 5
print(arr.shape)
print(arr)
print(arr.ndim)

(10, 5)
[[48 99 80 81 76]
 [ 6 75 16 37 15]
 [92 84 26 79 61]
 [48 41 32 72 11]
 [49 67 38 13  7]
 [80 70 60 38 23]
 [59 32 27 76 97]
 [32 98 58 56 49]
 [92 95 13 46 34]
 [79 33 89 21 78]]
2


In [2]:
# Changing shape
b = arr.reshape(2,25)
print(b.shape)
print(b)
print(b.ndim)

(2, 25)
[[48 99 80 81 76  6 75 16 37 15 92 84 26 79 61 48 41 32 72 11 49 67 38 13
   7]
 [80 70 60 38 23 59 32 27 76 97 32 98 58 56 49 92 95 13 46 34 79 33 89 21
  78]]
2


In [3]:
# Changing Dimension
# 1D
flatten = b.flatten()
print(flatten)

[48 99 80 81 76  6 75 16 37 15 92 84 26 79 61 48 41 32 72 11 49 67 38 13
  7 80 70 60 38 23 59 32 27 76 97 32 98 58 56 49 92 95 13 46 34 79 33 89
 21 78]


In [4]:
column_wise_flattening = np.ravel(b, order= 'F')
print(column_wise_flattening)

[48 80 99 70 80 60 81 38 76 23  6 59 75 32 16 27 37 76 15 97 92 32 84 98
 26 58 79 56 61 49 48 92 41 95 32 13 72 46 11 34 49 79 67 33 38 89 13 21
  7 78]


In [5]:
a = np.random.randint(1,10, size = (2,3))
b = np.random.randint(20,30, size = (2,3))

print(a)
print(b)

[[3 1 5]
 [7 8 6]]
[[21 29 26]
 [22 22 21]]


In [6]:
# Concatenat


con = np.concatenate((a,b), axis = 0) #row wise
print(con)
con_c = np.concatenate((a,b), axis = 1) #Column wise
print(con_c)

[[ 3  1  5]
 [ 7  8  6]
 [21 29 26]
 [22 22 21]]
[[ 3  1  5 21 29 26]
 [ 7  8  6 22 22 21]]


# 11.2 ndarray Manipulation - 2


In [7]:
# Transpose
mat = np.array([[100,20,30],[30,400,50]])

Transpose = mat.T
print(Transpose)

[[100  30]
 [ 20 400]
 [ 30  50]]


In [8]:
#Array split

a = np.random.randint(1,10, size= (10,))
print(a)

[7 7 8 1 3 3 2 2 4 8]


In [9]:
splitted_array = np.array_split(a, 3)
print(splitted_array)

[array([7, 7, 8, 1], dtype=int32), array([3, 3, 2], dtype=int32), array([2, 4, 8], dtype=int32)]


# 11.3 ndarray Arithmetic Operators and Mathematical function

In [10]:
#mathematical operator
#Faster for vectorization
x = np.array([10,20,30,40])
y = np.array([2,3,4,5])

add = x+y

print(add)

sub = x-y

print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

rem = x%y
print(rem)

[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [11]:
#mathematical function

#trigonometry
sin_val = np.sin(x)
cos_val = np.cos(x)
tan_val = np.tan(x)

print(sin_val)
print(cos_val)
print(tan_val)


[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493]


In [12]:
#Converting Degree<->Radian
#radian to degree
deg_con = np.rad2deg(x)
print(deg_con)
#degree to radian
red_con = np.deg2rad(x)
print(red_con)

[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]
[0.17453293 0.34906585 0.52359878 0.6981317 ]


In [13]:
#log
print(x)
bas_10_log = np.log10(x)
print(bas_10_log)

bas_2_log = np.log2(x)
print(bas_2_log)

[10 20 30 40]
[1.         1.30103    1.47712125 1.60205999]
[3.32192809 4.32192809 4.9068906  5.32192809]


In [14]:
#Square root

sqr_rt = np.sqrt(x)
print(sqr_rt)

sum = np.sum(x)
print(sum)
c_sum = np.cumulative_sum(x)
print(c_sum)

[3.16227766 4.47213595 5.47722558 6.32455532]
100
[ 10  30  60 100]


# 11.4 Numpy Broadcasting

In [15]:
x  = np.array([10,8,16,10])

result = x+2
print(result)

[12 10 18 12]


In [16]:
print(mat)
matrix = mat
result = matrix + 2
print(result)

vector = np.array([1,2,3])
result = matrix + vector
print(result)

[[100  20  30]
 [ 30 400  50]]
[[102  22  32]
 [ 32 402  52]]
[[101  22  33]
 [ 31 402  53]]


# 11.5 Numpy Logical Functions

In [17]:
greatter_than = x>y
print(greatter_than)

[ True  True  True  True]


In [18]:
print(np.all(greatter_than))
print(np.any(greatter_than))

True
True


# 11.6 ndarray Sorting


In [19]:
#Inplace sorting

print(x)

z = x.copy()
print(z)
z.sort()

print(z)

[10  8 16 10]
[10  8 16 10]
[ 8 10 10 16]


In [20]:
# Copy sort
print(x)
sort_arr = np.sort(x)
print(sort_arr)
print(x)

[10  8 16 10]
[ 8 10 10 16]
[10  8 16 10]


In [21]:
#2D array sorting

print(mat)

n_mat = mat
#horizon  axis = 1

hor_sort=np.sort(mat, axis=1)
print(hor_sort)

#verticat
vert_sort = np.sort(mat, axis=0)
print(vert_sort)


[[100  20  30]
 [ 30 400  50]]
[[ 20  30 100]
 [ 30  50 400]]
[[ 30  20  30]
 [100 400  50]]


# 11.7 ndarray Searching

In [22]:
print(x)

index = np.where(x==16)
print(index)
index = np.where(x>8)#return index
print(index)

[10  8 16 10]
(array([2]),)
(array([0, 2, 3]),)


In [23]:
#If value is less than 8 , rewrite as 0
arr = np.where(x>8,x,0)#returns array
print(arr)

[10  0 16 10]


In [24]:
print(mat)

[[100  20  30]
 [ 30 400  50]]


In [25]:
index = np.where(mat>80)#return index
print(index)
index = np.where(mat>80,mat,0)#return index
print(index)

(array([0, 1]), array([0, 1]))
[[100   0   0]
 [  0 400   0]]


In [26]:
#max value index
print(x)
max_val = np.argmax(x)
print(max_val)

[10  8 16 10]
2


In [27]:
#min value index
print(x)
min_val = np.argmin(x)
print(min_val)

[10  8 16 10]
1


# 11.8 ndarray Counting

In [28]:
arr_1d = np.random.randint(1,100, size=(100,))
print(arr_1d)

[23 50 92 81 62 41 34 37 91 11 84 78 38 81 82 97 56 20 87 46 31 49 39 61
 50 69 18 81 17 79 50 30 55 83 31 14 70 86 31 59 63 54 80 78 65 44 79 57
 32 44 44 66 19  7 37 12 92 90 39 50 71  2 75 13 32 99 95  7 97 22 11 41
 28 97  4 13 37 64  9 53 32 49 90  5 18 14 65 43 17 87 12 16  1 22 41 39
 29 14 22 32]


In [29]:
value_gr_60 = np.count_nonzero(arr_1d==7)
print(value_gr_60)

2


In [30]:
unq_val,count = np.unique(arr_1d,return_counts=True)
print(unq_val)
print(count)

[ 1  2  4  5  7  9 11 12 13 14 16 17 18 19 20 22 23 28 29 30 31 32 34 37
 38 39 41 43 44 46 49 50 53 54 55 56 57 59 61 62 63 64 65 66 69 70 71 75
 78 79 80 81 82 83 84 86 87 90 91 92 95 97 99]
[1 1 1 1 2 1 2 2 2 3 1 2 2 1 1 3 1 1 1 1 3 4 1 3 1 3 3 1 3 1 2 4 1 1 1 1 1
 1 1 1 1 1 2 1 1 1 1 1 2 2 1 3 1 1 1 1 2 2 1 2 1 3 1]


# 11.9 Statistical function

In [34]:
#data loading
data = np.genfromtxt('students_scores.csv',delimiter=',', skip_header=1)
print(data)


[[  1.  56.  97.  42.]
 [  2.  44.  81.  55.]
 [  3.  78.  88.  72.]
 [  4.  90.  97.  79.]
 [  5.  83.  98.  40.]
 [  6.  60.  49.  91.]
 [  7.  83.  96.  58.]
 [  8.  68.  53.  87.]
 [  9.  74.  62.  88.]
 [ 10.  64.  56.  93.]
 [ 11.  47.  43.  60.]
 [ 12.  84.  56.  42.]
 [ 13.  74.  51.  67.]
 [ 14.  92.  43.  59.]
 [ 15.  86.  98.  59.]
 [ 16.  87.  94.  52.]
 [ 17.  57.  83.  59.]
 [ 18.  57.  83.  51.]
 [ 19.  43.  99.  95.]
 [ 20.  98.  48.  69.]
 [ 21.  80.  57.  65.]
 [ 22.  45.  64.  81.]
 [ 23.  86.  97.  73.]
 [ 24.  50.  86.  98.]
 [ 25.  75.  49.  91.]
 [ 26.  40.  86.  98.]
 [ 27.  97.  80.  67.]
 [ 28.  95.  46.  56.]
 [ 29.  90.  87.  49.]
 [ 30.  87.  60.  96.]
 [ 31.  58.  98.  76.]
 [ 32.  45.  42.  98.]
 [ 33.  93.  53.  86.]
 [ 34.  54.  97.  56.]
 [ 35.  89.  55.  76.]
 [ 36.  77.  46.  56.]
 [ 37.  71.  45.  89.]
 [ 38.  54.  96.  75.]
 [ 39.  64.  83.  77.]
 [ 40.  84.  80.  42.]
 [ 41.  69.  81.  72.]
 [ 42.  54.  81.  88.]
 [ 43.  40.  62.  75.]
 [ 44.  44.

In [43]:
#slicing
math_marks = data[::,1:2]
print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)
min_math_marks = np.min(math_marks)
print(min_math_marks)
avg_math_marks = np.mean(math_marks)
print(avg_math_marks)
median_math_marks = np.median(math_marks)
print(median_math_marks)

#Standard Deviation

std_math_marks = np.std(math_marks)
print(std_math_marks)


[[56. 44. 78. 90. 83. 60. 83. 68. 74. 64. 47. 84. 74. 92. 86. 87. 57. 57.
  43. 98. 80. 45. 86. 50. 75. 40. 97. 95. 90. 87. 58. 45. 93. 54. 89. 77.
  71. 54. 64. 84. 69. 54. 40. 44. 71. 71. 43. 59. 89. 50. 85. 65. 42. 52.
  96. 55. 66. 82. 99. 56. 51. 64. 67. 59. 95. 68. 40. 72. 85. 85. 44. 87.
  66. 71. 89. 56. 57. 58. 80. 92. 87. 91. 66. 65. 77. 86. 66. 46. 68. 52.
  59. 55. 43. 96. 76. 84. 62. 97. 55. 53.]]
99.0
40.0
69.17
68.0
17.122531938939403
