# 11.1 ndarray Manipulation -1


In [23]:
import numpy as np
arr = np.random.randint(1,100, size = (10,5)) #sample = 10, feature = 5
print(arr.shape)
print(arr)
print(arr.ndim)

(10, 5)
[[44 81 49 90 53]
 [23 81 13 98 90]
 [ 2  3 87 78 44]
 [45 84 33 78 11]
 [32 40 66 20 76]
 [32 11 29 16  1]
 [41 70 20 95 74]
 [ 8  3 31 86 42]
 [64 68 34 58 88]
 [ 3 68 95 78 87]]
2


In [24]:
# Changing shape
b = arr.reshape(2,25)
print(b.shape)
print(b)
print(b.ndim)

(2, 25)
[[44 81 49 90 53 23 81 13 98 90  2  3 87 78 44 45 84 33 78 11 32 40 66 20
  76]
 [32 11 29 16  1 41 70 20 95 74  8  3 31 86 42 64 68 34 58 88  3 68 95 78
  87]]
2


In [26]:
# Changing Dimension
# 1D
flatten = b.flatten()
print(flatten)

[44 81 49 90 53 23 81 13 98 90  2  3 87 78 44 45 84 33 78 11 32 40 66 20
 76 32 11 29 16  1 41 70 20 95 74  8  3 31 86 42 64 68 34 58 88  3 68 95
 78 87]


In [29]:
column_wise_flattening = np.ravel(b, order= 'F')
print(column_wise_flattening)

[44 32 81 11 49 29 90 16 53  1 23 41 81 70 13 20 98 95 90 74  2  8  3  3
 87 31 78 86 44 42 45 64 84 68 33 34 78 58 11 88 32  3 40 68 66 95 20 78
 76 87]


In [30]:
a = np.random.randint(1,10, size = (2,3))
b = np.random.randint(20,30, size = (2,3))

print(a)
print(b)

[[1 9 7]
 [3 7 7]]
[[25 24 22]
 [22 21 29]]


In [33]:
# Concatenat


con = np.concatenate((a,b), axis = 0) #row wise
print(con)
con_c = np.concatenate((a,b), axis = 1) #Column wise
print(con_c)

[[ 1  9  7]
 [ 3  7  7]
 [25 24 22]
 [22 21 29]]
[[ 1  9  7 25 24 22]
 [ 3  7  7 22 21 29]]
