# 11.1 ndarray Manipulation -1


In [38]:
import numpy as np
arr = np.random.randint(1,100, size = (10,5)) #sample = 10, feature = 5
print(arr.shape)
print(arr)
print(arr.ndim)

(10, 5)
[[47 71 62 95 46]
 [84  5 56 60 30]
 [61 62 34 16 48]
 [95 57 17 11 84]
 [96 58 89 73 38]
 [13 67 39 26 11]
 [41 36  6 29 10]
 [84 12 25 56 32]
 [64 31 50  1 25]
 [76 30 17 12 43]]
2


In [39]:
# Changing shape
b = arr.reshape(2,25)
print(b.shape)
print(b)
print(b.ndim)

(2, 25)
[[47 71 62 95 46 84  5 56 60 30 61 62 34 16 48 95 57 17 11 84 96 58 89 73
  38]
 [13 67 39 26 11 41 36  6 29 10 84 12 25 56 32 64 31 50  1 25 76 30 17 12
  43]]
2


In [40]:
# Changing Dimension
# 1D
flatten = b.flatten()
print(flatten)

[47 71 62 95 46 84  5 56 60 30 61 62 34 16 48 95 57 17 11 84 96 58 89 73
 38 13 67 39 26 11 41 36  6 29 10 84 12 25 56 32 64 31 50  1 25 76 30 17
 12 43]


In [41]:
column_wise_flattening = np.ravel(b, order= 'F')
print(column_wise_flattening)

[47 13 71 67 62 39 95 26 46 11 84 41  5 36 56  6 60 29 30 10 61 84 62 12
 34 25 16 56 48 32 95 64 57 31 17 50 11  1 84 25 96 76 58 30 89 17 73 12
 38 43]


In [42]:
a = np.random.randint(1,10, size = (2,3))
b = np.random.randint(20,30, size = (2,3))

print(a)
print(b)

[[7 6 9]
 [9 2 6]]
[[25 25 22]
 [27 23 24]]


In [43]:
# Concatenat


con = np.concatenate((a,b), axis = 0) #row wise
print(con)
con_c = np.concatenate((a,b), axis = 1) #Column wise
print(con_c)

[[ 7  6  9]
 [ 9  2  6]
 [25 25 22]
 [27 23 24]]
[[ 7  6  9 25 25 22]
 [ 9  2  6 27 23 24]]


# 11.2 ndarray Manipulation - 2


In [44]:
# Transpose
mat = np.array([[10,20,30],[30,40,50]])

Transpose = mat.T
print(Transpose)

[[10 30]
 [20 40]
 [30 50]]


In [45]:
#Array split

a = np.random.randint(1,10, size= (10,))
print(a)

[2 2 9 9 2 9 1 2 1 1]


In [46]:
splitted_array = np.array_split(a, 3)
print(splitted_array)

[array([2, 2, 9, 9], dtype=int32), array([2, 9, 1], dtype=int32), array([2, 1, 1], dtype=int32)]


# 11.3 ndarray Arithmetic Operators and Mathematical function

In [47]:
#mathematical operator
#Faster for vectorization
x = np.array([10,20,30,40])
y = np.array([2,3,4,5])

add = x+y

print(add)

sub = x-y

print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

rem = x%y
print(rem)

[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [48]:
#mathematical function

#trigonometry
sin_val = np.sin(x)
cos_val = np.cos(x)
tan_val = np.tan(x)

print(sin_val)
print(cos_val)
print(tan_val)


[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493]


In [49]:
#Converting Degree<->Radian
#radian to degree
deg_con = np.rad2deg(x)
print(deg_con)
#degree to radian
red_con = np.deg2rad(x)
print(red_con)

[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]
[0.17453293 0.34906585 0.52359878 0.6981317 ]


In [50]:
#log
print(x)
bas_10_log = np.log10(x)
print(bas_10_log)

bas_2_log = np.log2(x)
print(bas_2_log)

[10 20 30 40]
[1.         1.30103    1.47712125 1.60205999]
[3.32192809 4.32192809 4.9068906  5.32192809]


In [51]:
#Square root

sqr_rt = np.sqrt(x)
print(sqr_rt)

sum = np.sum(x)
print(sum)
c_sum = np.cumulative_sum(x)
print(c_sum)

[3.16227766 4.47213595 5.47722558 6.32455532]
100
[ 10  30  60 100]


# 11.4 Numpy Broadcasting

In [52]:
x  = np.array([10,8,16,100])

result = x+2
print(result)

[ 12  10  18 102]


In [53]:
print(mat)
matrix = mat
result = matrix + 2
print(result)

vector = np.array([1,2,3])
result = matrix + vector
print(result)

[[10 20 30]
 [30 40 50]]
[[12 22 32]
 [32 42 52]]
[[11 22 33]
 [31 42 53]]


# 11.5 Numpy Logical Functions

In [58]:
greatter_than = x>y
print(greatter_than)

[ True  True  True  True]


In [60]:
print(np.all(greatter_than))
print(np.any(greatter_than))

True
True
