# 11.1 ndarray Manipulation -1


In [1]:
import numpy as np
arr = np.random.randint(1,100, size = (10,5)) #sample = 10, feature = 5
print(arr.shape)
print(arr)
print(arr.ndim)

(10, 5)
[[ 8  6 98 41 69]
 [77  8  2 15 65]
 [78 73 53 61 79]
 [54  2  5 63 75]
 [12 87 62  3 77]
 [41 10  3 64 11]
 [91 50 98  7 59]
 [14 54 49 52 25]
 [72 72 16 81 18]
 [40 25 75 49 81]]
2


In [2]:
# Changing shape
b = arr.reshape(2,25)
print(b.shape)
print(b)
print(b.ndim)

(2, 25)
[[ 8  6 98 41 69 77  8  2 15 65 78 73 53 61 79 54  2  5 63 75 12 87 62  3
  77]
 [41 10  3 64 11 91 50 98  7 59 14 54 49 52 25 72 72 16 81 18 40 25 75 49
  81]]
2


In [3]:
# Changing Dimension
# 1D
flatten = b.flatten()
print(flatten)

[ 8  6 98 41 69 77  8  2 15 65 78 73 53 61 79 54  2  5 63 75 12 87 62  3
 77 41 10  3 64 11 91 50 98  7 59 14 54 49 52 25 72 72 16 81 18 40 25 75
 49 81]


In [4]:
column_wise_flattening = np.ravel(b, order= 'F')
print(column_wise_flattening)

[ 8 41  6 10 98  3 41 64 69 11 77 91  8 50  2 98 15  7 65 59 78 14 73 54
 53 49 61 52 79 25 54 72  2 72  5 16 63 81 75 18 12 40 87 25 62 75  3 49
 77 81]


In [5]:
a = np.random.randint(1,10, size = (2,3))
b = np.random.randint(20,30, size = (2,3))

print(a)
print(b)

[[3 8 4]
 [1 2 8]]
[[29 29 21]
 [29 29 22]]


In [6]:
# Concatenat


con = np.concatenate((a,b), axis = 0) #row wise
print(con)
con_c = np.concatenate((a,b), axis = 1) #Column wise
print(con_c)

[[ 3  8  4]
 [ 1  2  8]
 [29 29 21]
 [29 29 22]]
[[ 3  8  4 29 29 21]
 [ 1  2  8 29 29 22]]


# 11.2 ndarray Manipulation - 2


In [7]:
# Transpose
mat = np.array([[10,20,30],[30,40,50]])

Transpose = mat.T
print(Transpose)

[[10 30]
 [20 40]
 [30 50]]


In [8]:
#Array split

a = np.random.randint(1,10, size= (10,))
print(a)

[1 8 9 2 3 9 3 8 4 4]


In [9]:
splitted_array = np.array_split(a, 3)
print(splitted_array)

[array([1, 8, 9, 2], dtype=int32), array([3, 9, 3], dtype=int32), array([8, 4, 4], dtype=int32)]


# 11.3 ndarray Arithmetic Operators and Mathematical function

In [10]:
#mathematical operator
#Faster for vectorization
x = np.array([10,20,30,40])
y = np.array([2,3,4,5])

add = x+y

print(add)

sub = x-y

print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

rem = x%y
print(rem)

[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [11]:
#mathematical function

#trigonometry
sin_val = np.sin(x)
cos_val = np.cos(x)
tan_val = np.tan(x)

print(sin_val)
print(cos_val)
print(tan_val)


[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493]


In [13]:
#Converting Degree<->Radian
#radian to degree
deg_con = np.rad2deg(x)
print(deg_con)
#degree to radian
red_con = np.deg2rad(x)
print(red_con)

[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]
[0.17453293 0.34906585 0.52359878 0.6981317 ]


In [21]:
#log
print(x)
bas_10_log = np.log10(x)
print(bas_10_log)

bas_2_log = np.log2(x)
print(bas_2_log)

[10 20 30 40]
[1.         1.30103    1.47712125 1.60205999]
[3.32192809 4.32192809 4.9068906  5.32192809]


In [27]:
#Square root

sqr_rt = np.sqrt(x)
print(sqr_rt)

sum = np.sum(x)
print(sum)
c_sum = np.cumulative_sum(x)
print(c_sum)

[3.16227766 4.47213595 5.47722558 6.32455532]
100
[ 10  30  60 100]
