# 11.1 ndarray Manipulation -1


In [2]:
import numpy as np
arr = np.random.randint(1,100, size = (10,5)) #sample = 10, feature = 5
print(arr.shape)
print(arr)
print(arr.ndim)

(10, 5)
[[62 50 72 90 85]
 [69  8 24 27 67]
 [86 26 14 26 73]
 [24  3 91 92 40]
 [79 27 63 63 96]
 [54 12 36 23 89]
 [55 16 77  2 23]
 [57 76 20 13 32]
 [42 24 91 17 24]
 [51 11 69 71 22]]
2


In [3]:
# Changing shape
b = arr.reshape(2,25)
print(b.shape)
print(b)
print(b.ndim)

(2, 25)
[[62 50 72 90 85 69  8 24 27 67 86 26 14 26 73 24  3 91 92 40 79 27 63 63
  96]
 [54 12 36 23 89 55 16 77  2 23 57 76 20 13 32 42 24 91 17 24 51 11 69 71
  22]]
2


In [4]:
# Changing Dimension
# 1D
flatten = b.flatten()
print(flatten)

[62 50 72 90 85 69  8 24 27 67 86 26 14 26 73 24  3 91 92 40 79 27 63 63
 96 54 12 36 23 89 55 16 77  2 23 57 76 20 13 32 42 24 91 17 24 51 11 69
 71 22]


In [5]:
column_wise_flattening = np.ravel(b, order= 'F')
print(column_wise_flattening)

[62 54 50 12 72 36 90 23 85 89 69 55  8 16 24 77 27  2 67 23 86 57 26 76
 14 20 26 13 73 32 24 42  3 24 91 91 92 17 40 24 79 51 27 11 63 69 63 71
 96 22]


In [6]:
a = np.random.randint(1,10, size = (2,3))
b = np.random.randint(20,30, size = (2,3))

print(a)
print(b)

[[3 9 5]
 [4 5 9]]
[[29 20 24]
 [21 29 22]]


In [7]:
# Concatenat


con = np.concatenate((a,b), axis = 0) #row wise
print(con)
con_c = np.concatenate((a,b), axis = 1) #Column wise
print(con_c)

[[ 3  9  5]
 [ 4  5  9]
 [29 20 24]
 [21 29 22]]
[[ 3  9  5 29 20 24]
 [ 4  5  9 21 29 22]]


# 11.2 ndarray Manipulation - 2


In [10]:
# Transpose
mat = np.array([[10,20,30],[30,40,50]])

Transpose = mat.T
print(Transpose)

[[10 30]
 [20 40]
 [30 50]]


In [ ]:
#Array split

a = np.random.randint(1,10, size= (10,))
print(a)

[3 6 5 6 8 8 2 1 8 4]


In [24]:
splitted_array = np.array_split(a, 3)
print(splitted_array)

[array([3, 6, 5, 6], dtype=int32), array([8, 8, 2], dtype=int32), array([1, 8, 4], dtype=int32)]
