1. https://www.deep-ml.com/problems/4

2. https://www.deep-ml.com/problems/1


In [1]:
import numpy as np

def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:
  mat= np.array(matrix)
  if mode == 'row':
    means = np.mean(matrix, axis = 1).tolist()
  else:
    means = np.mean(matrix, axis = 0).tolist()
  return means


In [2]:
import numpy as np
def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
  a = np.array(a)
  b = np.array(b)
  shape_a = a.shape
  if shape_a[1] != b.size:
    return -1
    
  dot = np.dot(a,b).tolist()
  return dot

In [3]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print(b.shape)

(2, 3)


In [4]:
print(np.sin(np.pi/2))

1.0


In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [6]:
a = np.array([1,2,3])
print(np.sort(a))

[1 2 3]


In [7]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_p = np.dot(A,B)
print(dot_p)


[[19 22]
 [43 50]]


1. https://www.deep-ml.com/problems/2

In [9]:
import numpy as np
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
  b = np.transpose(a).tolist()
  return b