1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.

In [1]:
import numpy as np
# 1D Array
D1_arr = np.array([1,2,3,4,5,6])
print(f"1D Array: \n{D1_arr}\n")

# 2D Array
D2_arr = np.array([[1,2,3], #Row 1
                   [4,5,6]])#Row 2
print(f"2D Array: \n{D2_arr}\n")

# 3D Array
D3_arr = np.array([
                  #First Floor
                  [[1,2,3], #Row 1
                   [4,5,6]],#Row 2
                   #Second Floor
                   [[7,8,9], #Row 1
                   [10,11,12]]#Row 2
                   ])
print(f"3D Array: \n{D3_arr}")

1D Array: 
[1 2 3 4 5 6]

2D Array: 
[[1 2 3]
 [4 5 6]]

3D Array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


2 . Create:

an array of zeros of shape (3,3)


an array of ones of shape (2,5)


an array filled with 7


In [9]:
#an array of zeros of shape (3,3)
import numpy as np
arr_0 = np.zeros((3,3), dtype= np.int64)
print(f"An array of zeros of shape (3,3): \n{arr_0} \n")

#an array of ones of shape (2,5)
arr_1 = np.ones((2,5), dtype= np.int64)
print(f"An array of ones of shape (2,5): \n{arr_1} \n")

#An array filled with 7
arr_7 = np.full((5,),7)
print(f"An array filled with 7: \n{arr_7}\n")

An array of zeros of shape (3,3): 
[[0 0 0]
 [0 0 0]
 [0 0 0]] 

An array of ones of shape (2,5): 
[[1 1 1 1 1]
 [1 1 1 1 1]] 

An array filled with 7: 
[7 7 7 7 7]



3 . Create an array of even numbers between 10 and 50 using arange.


In [3]:
import numpy as np

even = np.arange(10,50,2)
print(even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


4 . Create a 4×4 matrix from 0–15. Then , extract:

the first row


the last column


a 2×2 subarray from the center


In [11]:
mat = np.arange(0,16).reshape(4,4)
print(mat)

frst_row = mat[0:1,]
lst_clmn = mat[::, 3:]
cntr_prtn = mat[1:3, 1:3]
print(f"\nFirst Row: \n{frst_row}")
print(f"\nLast Column: \n{lst_clmn}")
print(f"\n2x2 sub array from centere: \n{cntr_prtn}")



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

First Row: 
[[0 1 2 3]]

Last Column: 
[[ 3]
 [ 7]
 [11]
 [15]]

2x2 sub array from centere: 
[[ 5  6]
 [ 9 10]]


5 . Add a 1D array [1,2,3] to each row of a 3×3 matrix.


In [30]:
arr = np.random.randint(1,20, size= (3,3) )

In [40]:
c_arr = arr.copy()
print(f"Main Array: \n{c_arr}\n")
D1_arr = [1,2,3]
add_arr = c_arr + D1_arr
print(f"Added Array: \n{add_arr}\n")

Main Array: 
[[12 19 16]
 [ 9 12 10]
 [ 4 18  1]]

Added Array: 
[[13 21 19]
 [10 14 13]
 [ 5 20  4]]



6 . Given two arrays A and B, compute:

(A + B) / 2

A**2 + B**2


In [45]:
A = np.array([1,2,3,4,5])
B = np.array([2,3,4,54,6])

print(f"(A + B) / 2 : {(A+B)/2}")
print(f"A**2 + B**2 : {(A**2)+ (B**2)}")

(A + B) / 2 : [ 1.5  2.5  3.5 29.   5.5]
A**2 + B**2 : [   5   13   25 2932   61]
