1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.

In [17]:
import numpy as np
# 1D Array
D1_arr = np.array([1,2,3,4,5,6])
print(f"1D Array: \n{D1_arr}\n")

# 2D Array
D2_arr = np.array([[1,2,3], #Row 1
                   [4,5,6]])#Row 2
print(f"2D Array: \n{D2_arr}\n")

# 3D Array
D3_arr = np.array([
                  #First Floor
                  [[1,2,3], #Row 1
                   [4,5,6]],#Row 2
                   #Second Floor
                   [[7,8,9], #Row 1
                   [10,11,12]]#Row 2
                   ])
print(f"3D Array: \n{D3_arr}")

1D Array: 
[1 2 3 4 5 6]

2D Array: 
[[1 2 3]
 [4 5 6]]

3D Array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
