# 10.2 ndarray and its attributes

In [59]:
#Normal Array
arr = [1,2,3]
print(arr * 5)
arr = [x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [60]:
# With Numpy NdArray
import numpy as np
arr1 = np.array([1,2,3])

arr1 = arr1 * 5

print(arr1)

[ 5 10 15]


In [61]:
# Declaring nd array
import numpy as np

#1d array

arr1 = np.array([1,2,3,4,5,6])

print(type(arr1))

#Dimensions
print(arr1.ndim)

#2d array
arr2 = np.array([[1,2,3], # row1
                 [4,5,6]]) #row 2

print(arr2.ndim)

#3d array(Multiple 2d array in a single array)

arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6] ],#row 2

    #2nd floor
    [ [1,2,3], # row1
      [4,5,6] ]#row 2
])

print(arr3.ndim)


<class 'numpy.ndarray'>
1
2
3


### Array attributes


In [62]:
#Dimension
print("Dimensions:")
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

print("Shapes:")
#Shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

print("Data Types:")
#Data types
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

print("Sizes")
#Size
print(arr1.size)
print(arr2.size)
print(arr3.size)

Dimensions:
1
2
3
Shapes:
(6,)
(2, 3)
(2, 2, 3)
Data Types:
int64
int64
int64
Sizes
6
6
12


# 10.3 Ndarray Data Type

In [63]:
arr = np.array([1,2,3])
print(arr.dtype) #By default int64 as 64-bit machine


arr = np.array([1,2,3.4,5.6])
print(arr.dtype) #By default float64 as 64-bit machine(double precision float value)



int64
float64


In [64]:
arr = np.array([1,2,3.4])
#Upcasted to float
print(arr.dtype)

float64


In [65]:
arr = np.array([1,2,3.4, 'h'])
#Upcasted to string
print(arr.dtype)

<U32


In [66]:
#Selecting a data type for an array
arr = np.array([1,2,3], dtype = np.int8)
print(arr.dtype)
print(arr)

arr = arr.astype(np.int16)
print(arr.dtype)
print(arr)


int8
[1 2 3]
int16
[1 2 3]


In [67]:
arr = np.array([1,2,3.4, 'h', True])
#Upcasted to string
print(arr.dtype)

<U32


# 10.4 ndarray creation from Existing data

In [68]:
#List to ndra
import numpy as np

lst = [10, 20, 30, 40, 40.5]
arr = np.array(lst, dtype=np.int32)
print(arr)
print(arr.dtype)

[10 20 30 40 40]
int32


In [69]:
#nested list to ndarray
matrix = [[1, 2, 3],
          [4, 5, 6]]

arr = np.array(matrix)
print(arr)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
int64


In [70]:
#Tuple to ndarray
tup = (10, 20, 30)
arr = np.array(tup)
print(arr)
print(arr.dtype)

[10 20 30]
int64


In [71]:
#set to ndarray
s = {10, 20, 30}
arr = np.array(s)
print(arr)
print(arr.dtype)

{10, 20, 30}
object


In [72]:
#From Dictionary
dc = {'a' : 10, 'b' : 20, 'c' : 30}
keys = dc.keys()
values = dc.values()
itm = dc.items()
print(keys)
print(values)
print(itm)

dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])


In [73]:
#Keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [74]:
#Values to ndarray
arr = np.array(list(values))
print(arr)
print(type(arr))
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int64
int16
(3,)
1
3


In [75]:
#Items to ndr
arr = np.array(list(itm))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6
