# 10.2 ndarray and its attributes

In [1]:
#Normal Array
arr = [1,2,3]
print(arr * 5)
arr = [x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [2]:
# With Numpy NdArray
import numpy as np
arr1 = np.array([1,2,3])

arr1 = arr1 * 5

print(arr1)

[ 5 10 15]


In [10]:
# Declaring nd array
import numpy as np

#1d array

arr1 = np.array([1,2,3,4,5,6])

print(type(arr1))

#Dimensions
print(arr1.ndim)

#2d array
arr2 = np.array([[1,2,3], # row1
                 [4,5,6]]) #row 2

print(arr2.ndim)

#3d array(Multiple 2d array in a single array)

arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6] ],#row 2

    #2nd floor
    [ [1,2,3], # row1
      [4,5,6] ]#row 2
])

print(arr3.ndim)


<class 'numpy.ndarray'>
1
2
3


### Array attributes


In [12]:
#Dimension
print("Dimensions:")
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

print("Shapes:")
#Shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

print("Data Types:")
#Data types
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

print("Sizes")
#Size
print(arr1.size)
print(arr2.size)
print(arr3.size)

Dimensions:
1
2
3
Shapes:
(6,)
(2, 3)
(2, 2, 3)
Data Types:
int64
int64
int64
Sizes
6
6
12


# 10.3 Ndarray Data Type

In [14]:
arr = np.array([1,2,3])
print(arr.dtype) #By default int64 as 64-bit machine


arr = np.array([1,2,3.4,5.6])
print(arr.dtype) #By default float64 as 64-bit machine(double precision float value)



int64
float64


In [15]:
arr = np.array([1,2,3.4])
#Upcasted to float
print(arr.dtype)

float64


In [17]:
arr = np.array([1,2,3.4, 'h'])
#Upcasted to string
print(arr.dtype)

<U32


In [24]:
#Selecting a data type for an array
arr = np.array([1,2,3], dtype = np.int8)
print(arr.dtype)
print(arr)

arr = arr.astype(np.int16)
print(arr.dtype)
print(arr)


int8
[1 2 3]
int16
[1 2 3]


In [26]:
arr = np.array([1,2,3.4, 'h', True])
#Upcasted to string
print(arr.dtype)

<U32
