# 10.2 ndarray and its attributes

In [234]:
#Normal Array
arr = [1,2,3]
print(arr * 5)
arr = [x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [235]:
# With Numpy NdArray
import numpy as np
arr1 = np.array([1,2,3])

arr1 = arr1 * 5

print(arr1)

[ 5 10 15]


In [236]:
# Declaring nd array
import numpy as np

#1d array

arr1 = np.array([1,2,3,4,5,6])

print(type(arr1))

#Dimensions
print(arr1.ndim)

#2d array
arr2 = np.array([[1,2,3], # row1
                 [4,5,6]]) #row 2

print(arr2.ndim)

#3d array(Multiple 2d array in a single array)

arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6] ],#row 2

    #2nd floor
    [ [1,2,3], # row1
      [4,5,6] ]#row 2
])

print(arr3.ndim)


<class 'numpy.ndarray'>
1
2
3


### Array attributes


In [237]:
#Dimension
print("Dimensions:")
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

print("Shapes:")
#Shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

print("Data Types:")
#Data types
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

print("Sizes")
#Size
print(arr1.size)
print(arr2.size)
print(arr3.size)

Dimensions:
1
2
3
Shapes:
(6,)
(2, 3)
(2, 2, 3)
Data Types:
int64
int64
int64
Sizes
6
6
12


# 10.3 Ndarray Data Type

In [238]:
arr = np.array([1,2,3])
print(arr.dtype) #By default int64 as 64-bit machine


arr = np.array([1,2,3.4,5.6])
print(arr.dtype) #By default float64 as 64-bit machine(double precision float value)



int64
float64


In [239]:
arr = np.array([1,2,3.4])
#Upcasted to float
print(arr.dtype)

float64


In [240]:
arr = np.array([1,2,3.4, 'h'])
#Upcasted to string
print(arr.dtype)

<U32


In [241]:
#Selecting a data type for an array
arr = np.array([1,2,3], dtype = np.int8)
print(arr.dtype)
print(arr)

arr = arr.astype(np.int16)
print(arr.dtype)
print(arr)


int8
[1 2 3]
int16
[1 2 3]


In [242]:
arr = np.array([1,2,3.4, 'h', True])
#Upcasted to string
print(arr.dtype)

<U32


# 10.4 ndarray creation from Existing data

In [243]:
#List to ndra
import numpy as np

lst = [10, 20, 30, 40, 40.5]
arr = np.array(lst, dtype=np.int32)
print(arr)
print(arr.dtype)

[10 20 30 40 40]
int32


In [244]:
#nested list to ndarray
matrix = [[1, 2, 3],
          [4, 5, 6]]

arr = np.array(matrix)
print(arr)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
int64


In [245]:
#Tuple to ndarray
tup = (10, 20, 30)
arr = np.array(tup)
print(arr)
print(arr.dtype)

[10 20 30]
int64


In [246]:
#set to ndarray
s = {10, 20, 30}
arr = np.array(s)
print(arr)
print(arr.dtype)

{10, 20, 30}
object


In [247]:
#From Dictionary
dc = {'a' : 10, 'b' : 20, 'c' : 30}
keys = dc.keys()
values = dc.values()
itm = dc.items()
print(keys)
print(values)
print(itm)

dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])


In [248]:
#Keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [249]:
#Values to ndarray
arr = np.array(list(values))
print(arr)
print(type(arr))
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int64
int16
(3,)
1
3


In [250]:
#Items to ndr
arr = np.array(list(itm))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


# 10.5 ndarray creation from scratch

In [251]:
#np,zeros

arr = np.zeros((2,3), dtype= np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(2, 3)
2
6


In [252]:
#From existing shape
arr = np.zeros_like(arr3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
<class 'numpy.ndarray'>
int64
(2, 2, 3)
3
12


In [253]:
#np.one
arr = np.ones((3,4,3), dtype= np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int8
(3, 4, 3)
3
36


In [254]:
#From existing
arr = np.ones_like(arr3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int64
(2, 2, 3)
3
12


In [255]:
#np.empty

arr = np.empty((2,3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [256]:
#From existing
arr = np.empty_like(arr3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int64
(2, 2, 3)
3
12


In [257]:
#np.full
arr = np.full((2,3), np.inf)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [258]:
#From existing

arr = np.full_like(arr3, np.inf, dtype= np.float64)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
<class 'numpy.ndarray'>
float64
(2, 2, 3)
3
12


# 10.6 ndarray generation with random values

In [259]:
# np.random.rand(shape)
import numpy as np
arr = np.random.rand(2,3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.21693927 0.3433806  0.92965847]
 [0.42187013 0.359181   0.61083011]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [260]:
# np.random.randint(shape)->integer

arr = np.random.randint(1,10, (2,3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[2 2 2]
 [2 8 5]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
6


In [261]:
# np.random.uniform(shape)->float

arr = np.random.uniform(50,100, (3,4))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[87.12351041 61.73470666 74.50293018 58.79871334]
 [59.46603063 50.87783188 54.42146476 72.89303652]
 [94.37304815 94.92230241 51.2952919  75.52196274]]
<class 'numpy.ndarray'>
float64
(3, 4)
2
12


# 10.7 ndarray creation from range

In [262]:
#np.arange(first, end, step)->similar to range
arr = np.arange(1,10,2)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[1 3 5 7 9]
<class 'numpy.ndarray'>
int64
(5,)
1
5


In [263]:
#Mtarix

arr = np.arange(1,10,1).reshape(3,3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2
9


In [264]:
#Linear space
arr = np.linspace(1,10,8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]
<class 'numpy.ndarray'>
float64
(8,)
1
8


In [265]:
# np.logcpace
arr = np.logspace(0,4,6, base = 2)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


# 10.8 creating diagonal and identity matrix

In [266]:
#Diagonal Matrix

di_ma= np.diag([1,2,3,4])
print(di_ma)
print(di_ma.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [267]:
#Identity  Matrix
id_ma = np.eye(4)
print(id_ma)
print(id_ma.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [268]:
#np.eye(row, column)
id_ma = np.eye(3,4)
print(id_ma)
print(id_ma.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
(3, 4)


In [269]:
#np.eye(row, column)
id_ma = np.eye(3,4,-1)
print(id_ma)
print(id_ma.shape)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
(3, 4)


# 10.9 ndarray Indexing and Slicing

In [270]:
#indexing

print(arr1)
print(arr2)

print(arr1[2])

arr1[2] = 100
print(arr1)

print(arr2[1][0])

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
3
[  1   2 100   4   5   6]
4


In [271]:
#slicing
#1d = arr[start:end:step]
arr1_mod = arr1[1:4].copy()
print(arr1_mod)



[  2 100   4]


In [272]:
#2d = arr[row start : row end: step , column_start: column_ened : step]
#getting a row
row_0 = arr2[0:1,]
row_1 = arr2[1: ,]
print(row_0)
print(row_1)

[[1 2 3]]
[[4 5 6]]


In [273]:
#Getting a column
col_0 = arr2[::, 0:1]
print(col_0)
col_1 = arr2[::, 1:2]
print(col_1)

[[1]
 [4]]
[[2]
 [5]]


In [274]:
#getting a portion

portion = arr2[::, 0:2]
print(portion)

[[1 2]
 [4 5]]


# 10.10 Ndarray Copy Advanced Indexing and Iteration

In [275]:
#Advance Indexing
lst = np.array([10,20,30,40])

values = lst[[0,3]]
print(values)

[10 40]


In [276]:
#For 2D array
print(arr2)
values = arr2[[0,1],[1,2]]
print(values)


[[1 2 3]
 [4 5 6]]
[2 6]


In [277]:
#Getting by boolean

bol_get = arr2[arr2>2].copy()
print(arr2)
arr2[arr2>2] = 100
print(arr2)
print(bol_get)

[[1 2 3]
 [4 5 6]]
[[  1   2 100]
 [100 100 100]]
[3 4 5 6]


In [289]:
#Iteration
arr = np.array([[10,20,30],[100,200,300]])
print(arr2)

for i in np.nditer(arr):
  print(i)

[[  1   2 100]
 [100 100 100]]
10
20
30
100
200
300


#Exam and Practice

In [298]:
arr = np.array([1,2,3,4,5])
arr[1:4] = 0
print(arr)

[1 0 0 0 5]
